<a href="https://colab.research.google.com/github/hemantk1121/pandas/blob/main/Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = [100,102,234]
series=pd.Series(data,index=["a","b","c"])
series.loc["c"]=500
series.iloc[1]=400
print(series[series>=200])

b    400
c    500
dtype: int64

In [ ]:
import pandas as pd
data=["bulbasar","hemant","shagun"]
series=pd.Series(data)
print(series)

0    bulbasar
1      hemant
2      shagun
dtype: object

In [ ]:
import pandas as pd
data={"Name":["udit","shagun","tushar"],
      "Age":[21,21,28],
}
df=pd.DataFrame(data,index=["employe 1","employe 2","employe 3"])
#new colume
df["job"]=["photographer","web devloper","gov.employe"]
new_rows=pd.DataFrame([
    {"Name":"sandy","Age":22,"job":"servent"},
    {"Name":"andy","Age":22,"job":"labour"}],index=["employe 4","employe 5"]
)
df=pd.concat([df,new_rows])


print(df)

             Name  Age           job
employe 1    udit   21  photographer
employe 2  shagun   21  web devloper
employe 3  tushar   28   gov.employe
employe 4   sandy   22       servent
employe 5    andy   22        labour

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Titanic-Dataset.csv to Titanic-Dataset.csv

In [ ]:
import pandas as pd
data=pd.read_csv("Titanic-Dataset.csv")
print(data)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [ ]:
print(data["Sex"])

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object

In [ ]:
print(data["Ticket"])

0             A/5 21171
1              PC 17599
2      STON/O2. 3101282
3                113803
4                373450
             ...
886              211536
887              112053
888          W./C. 6607
889              111369
890              370376
Name: Ticket, Length: 891, dtype: object

In [ ]:
print(data["Cabin"])

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [ ]:
print(data[['Name','Sex','Cabin']])

                                                  Name     Sex Cabin
0                              Braund, Mr. Owen Harris    male   NaN
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   C85
2                               Heikkinen, Miss. Laina  female   NaN
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  C123
4                             Allen, Mr. William Henry    male   NaN
..                                                 ...     ...   ...
886                              Montvila, Rev. Juozas    male   NaN
887                       Graham, Miss. Margaret Edith  female   B42
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN
889                              Behr, Mr. Karl Howell    male  C148
890                                Dooley, Mr. Patrick    male   NaN

[891 rows x 3 columns]

In [ ]:
import pandas as pd
data=pd.read_csv("Titanic-Dataset.csv",index_col="Name")
print(data)

                                                    PassengerId  Survived  \
Name
Braund, Mr. Owen Harris                                       1         0
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1
Heikkinen, Miss. Laina                                        3         1
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1
Allen, Mr. William Henry                                      5         0
...                                                         ...       ...
Montvila, Rev. Juozas                                       887         0
Graham, Miss. Margaret Edith                                888         1
Johnston, Miss. Catherine Helen "Carrie"                    889         0
Behr, Mr. Karl Howell                                       890         1
Dooley, Mr. Patrick                                         891         0

                                                    Pclass     Sex   Age  \
Name
Braund, Mr. Owen Harris                                  3    male  22.0
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0
Heikkinen, Miss. Laina                                   3  female  26.0
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0
Allen, Mr. William Henry                                 3    male  35.0
...                                                    ...     ...   ...
Montvila, Rev. Juozas                                    2    male  27.0
Graham, Miss. Margaret Edith                             1  female  19.0
Johnston, Miss. Catherine Helen "Carrie"                 3  female   NaN
Behr, Mr. Karl Howell                                    1    male  26.0
Dooley, Mr. Patrick                                      3    male  32.0

                                                    SibSp  Parch  \
Name
Braund, Mr. Owen Harris                                 1      0
Cumings, Mrs. John Bradley (Florence Briggs Tha...      1      0
Heikkinen, Miss. Laina                                  0      0
Futrelle, Mrs. Jacques Heath (Lily May Peel)            1      0
Allen, Mr. William Henry                                0      0
...                                                   ...    ...
Montvila, Rev. Juozas                                   0      0
Graham, Miss. Margaret Edith                            0      0
Johnston, Miss. Catherine Helen "Carrie"                1      2
Behr, Mr. Karl Howell                                   0      0
Dooley, Mr. Patrick                                     0      0

                                                              Ticket     Fare  \
Name
Braund, Mr. Owen Harris                                    A/5 21171   7.2500
Cumings, Mrs. John Bradley (Florence Briggs Tha...          PC 17599  71.2833
Heikkinen, Miss. Laina                              STON/O2. 3101282   7.9250
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  113803  53.1000
Allen, Mr. William Henry                                      373450   8.0500
...                                                              ...      ...
Montvila, Rev. Juozas                                         211536  13.0000
Graham, Miss. Margaret Edith                                  112053  30.0000
Johnston, Miss. Catherine Helen "Carrie"                  W./C. 6607  23.4500
Behr, Mr. Karl Howell                                         111369  30.0000
Dooley, Mr. Patrick                                           370376   7.7500

                                                   Cabin Embarked
Name
Braund, Mr. Owen Harris                              NaN        S
Cumings, Mrs. John Bradley (Florence Briggs Tha...   C85        C
Heikkinen, Miss. Laina                               NaN        S
Futrelle, Mrs. Jacques Heath (Lily May Peel)        C123        S
Allen, Mr. William Henry                             NaN        S
...                                                  ...      ...
Montvila, Rev. Juozas                                NaN        S
Graham, Miss. Margaret Edith                         B42        S
Johnston, Miss. Catherine Helen "Carrie"             NaN        S
Behr, Mr. Karl Howell                               C148        C
Dooley, Mr. Patrick                                  NaN        Q

[891 rows x 11 columns]

In [ ]:
print(data.iloc[1:11:2,1:3])

                                                    Survived  Pclass
Name
Cumings, Mrs. John Bradley (Florence Briggs Tha...         1       1
Futrelle, Mrs. Jacques Heath (Lily May Peel)               1       1
Moran, Mr. James                                           0       3
Palsson, Master. Gosta Leonard                             0       3
Nasser, Mrs. Nicholas (Adele Achem)                        1       2

In [ ]:
pokemon=input("enter the name:")
try:
  print(data.loc[pokemon])
except KeyError:
  print(f"{pokemon} not found")

enter the name:harsh
harsh not found

In [ ]:
gen=data[(data['Sex']=="male") &
          (data['Age']>20)]
print(gen)

                               PassengerId  Survived  Pclass   Sex   Age  \
Name
Braund, Mr. Owen Harris                  1         0       3  male  22.0
Allen, Mr. William Henry                 5         0       3  male  35.0
McCarthy, Mr. Timothy J                  7         0       1  male  54.0
Andersson, Mr. Anders Johan             14         0       3  male  39.0
Fynney, Mr. Joseph J                    21         0       2  male  35.0
...                                    ...       ...     ...   ...   ...
Banfield, Mr. Frederick James          884         0       2  male  28.0
Sutehall, Mr. Henry Jr                 885         0       3  male  25.0
Montvila, Rev. Juozas                  887         0       2  male  27.0
Behr, Mr. Karl Howell                  890         1       1  male  26.0
Dooley, Mr. Patrick                    891         0       3  male  32.0

                               SibSp  Parch            Ticket     Fare Cabin  \
Name
Braund, Mr. Owen Harris            1      0         A/5 21171   7.2500   NaN
Allen, Mr. William Henry           0      0            373450   8.0500   NaN
McCarthy, Mr. Timothy J            0      0             17463  51.8625   E46
Andersson, Mr. Anders Johan        1      5            347082  31.2750   NaN
Fynney, Mr. Joseph J               0      0            239865  26.0000   NaN
...                              ...    ...               ...      ...   ...
Banfield, Mr. Frederick James      0      0  C.A./SOTON 34068  10.5000   NaN
Sutehall, Mr. Henry Jr             0      0   SOTON/OQ 392076   7.0500   NaN
Montvila, Rev. Juozas              0      0            211536  13.0000   NaN
Behr, Mr. Karl Howell              0      0            111369  30.0000  C148
Dooley, Mr. Patrick                0      0            370376   7.7500   NaN

                              Embarked
Name
Braund, Mr. Owen Harris              S
Allen, Mr. William Henry             S
McCarthy, Mr. Timothy J              S
Andersson, Mr. Anders Johan          S
Fynney, Mr. Joseph J                 S
...                                ...
Banfield, Mr. Frederick James        S
Sutehall, Mr. Henry Jr               S
Montvila, Rev. Juozas                S
Behr, Mr. Karl Howell                C
Dooley, Mr. Patrick                  Q

[351 rows x 11 columns]

In [ ]:
print(data.mean(numeric_only=True))

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [ ]:
print(data.sum(numeric_only=True))

PassengerId    397386.0000
Survived          342.0000
Pclass           2057.0000
Age             21205.1700
SibSp             466.0000
Parch             340.0000
Fare            28693.9493
dtype: float64

In [ ]:
print(data.min(numeric_only=True))

PassengerId    1.00
Survived       0.00
Pclass         1.00
Age            0.42
SibSp          0.00
Parch          0.00
Fare           0.00
dtype: float64

In [ ]:
group=data.groupby('Sex')
print(group.mean(numeric_only=True))

        PassengerId  Survived    Pclass        Age     SibSp     Parch  \
Sex
female   431.028662  0.742038  2.159236  27.915709  0.694268  0.649682
male     454.147314  0.188908  2.389948  30.726645  0.429809  0.235702

             Fare
Sex
female  44.479818
male    25.523893

In [ ]:
group=data.groupby('Sex')
print(group['Ticket'].count())

Sex
female    314
male      577
Name: Ticket, dtype: int64

In [ ]:
group=data.groupby('Sex')
print(group['Age'].mean())

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [ ]:

data.loc[data["Survived"]==0]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",6,0,3,male,NaN,0,0,330877,8.4583,NaN,Q
"McCarthy, Mr. Timothy J",7,0,1,male,54.0,0,0,17463,51.8625,E46,S
"Palsson, Master. Gosta Leonard",8,0,3,male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Sutehall, Mr. Henry Jr",885,0,3,male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
"Rice, Mrs. William (Margaret Norton)",886,0,3,female,39.0,0,5,382652,29.1250,NaN,Q
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
data['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
data[data["Pclass"]==1]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"McCarthy, Mr. Timothy J",7,0,1,male,54.0,0,0,17463,51.8625,E46,S
"Bonnell, Miss. Elizabeth",12,1,1,female,58.0,0,0,113783,26.5500,C103,S
"Sloper, Mr. William Thompson",24,1,1,male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...
"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",872,1,1,female,47.0,1,1,11751,52.5542,D35,S
"Carlsson, Mr. Frans Olof",873,0,1,male,33.0,0,0,695,5.0000,B51 B53 B55,S
"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",880,1,1,female,56.0,0,1,11767,83.1583,C50,C
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
data.loc[data["Pclass"]==1].reset_index()[["Name","Age","Sex"]]

                                                  Name   Age     Sex
0    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
1         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
2                              McCarthy, Mr. Timothy J  54.0    male
3                             Bonnell, Miss. Elizabeth  58.0  female
4                         Sloper, Mr. William Thompson  28.0    male
..                                                 ...   ...     ...
211   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0  female
212                           Carlsson, Mr. Frans Olof  33.0    male
213      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0  female
214                       Graham, Miss. Margaret Edith  19.0  female
215                              Behr, Mr. Karl Howell  26.0    male

[216 rows x 3 columns]

In [ ]:
data.loc[data["Survived"]!=0].value_counts()

PassengerId  Survived  Pclass  Sex     Age   SibSp  Parch  Ticket    Fare     Cabin  Embarked
2            1         1       female  38.0  1      0      PC 17599  71.2833  C85    C           1
4            1         1       female  35.0  1      0      113803    53.1000  C123   S           1
11           1         3       female  4.0   1      1      PP 9549   16.7000  G6     S           1
12           1         1       female  58.0  0      0      113783    26.5500  C103   S           1
22           1         2       male    34.0  0      0      248698    13.0000  D56    S           1
                                                                                                ..
863          1         1       female  48.0  0      0      17466     25.9292  D17    S           1
872          1         1       female  47.0  1      1      11751     52.5542  D35    S           1
880          1         1       female  56.0  0      1      11767     83.1583  C50    C           1
888          1         1       female  19.0  0      0      112053    30.0000  B42    S           1
890          1         1       male    26.0  0      0      111369    30.0000  C148   C           1
Name: count, Length: 123, dtype: int64

In [ ]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
data.iloc[10:21]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Sandstrom, Miss. Marguerite Rut",11,1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
"Bonnell, Miss. Elizabeth",12,1,1,female,58.0,0,0,113783,26.5500,C103,S
"Saundercock, Mr. William Henry",13,0,3,male,20.0,0,0,A/5. 2151,8.0500,NaN,S
"Andersson, Mr. Anders Johan",14,0,3,male,39.0,1,5,347082,31.2750,NaN,S
"Vestrom, Miss. Hulda Amanda Adolfina",15,0,3,female,14.0,0,0,350406,7.8542,NaN,S
"Hewlett, Mrs. (Mary D Kingcome)",16,1,2,female,55.0,0,0,248706,16.0000,NaN,S
"Rice, Master. Eugene",17,0,3,male,2.0,4,1,382652,29.1250,NaN,Q
"Williams, Mr. Charles Eugene",18,1,2,male,NaN,0,0,244373,13.0000,NaN,S
"Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)",19,0,3,female,31.0,1,0,345763,18.0000,NaN,S
"Masselmani, Mrs. Fatima",20,1,3,female,NaN,0,0,2649,7.2250,NaN,C
"Fynney, Mr. Joseph J",21,0,2,male,35.0,0,0,239865,26.0000,NaN,S

In [ ]:
data[(data["Age"]>30) & (data["Sex"]=="male") & (data["Pclass"]==1)]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"McCarthy, Mr. Timothy J",7,0,1,male,54.0,0,0,17463,51.8625,E46,S
"Uruchurtu, Don. Manuel E",31,0,1,male,40.0,0,0,PC 17601,27.7208,NaN,C
"Holverson, Mr. Alexander Oskar",36,0,1,male,42.0,1,0,113789,52.0000,NaN,S
"Ostby, Mr. Engelhart Cornelius",55,0,1,male,65.0,0,1,113509,61.9792,B30,C
"Harris, Mr. Henry Birkhardt",63,0,1,male,45.0,1,0,36973,83.4750,C83,S
...,...,...,...,...,...,...,...,...,...,...,...
"Andrews, Mr. Thomas Jr",807,0,1,male,39.0,0,0,112050,0.0000,A36,S
"Reuchlin, Jonkheer. John George",823,0,1,male,38.0,0,0,19972,0.0000,NaN,S
"Daly, Mr. Peter Denis",858,1,1,male,51.0,0,0,113055,26.5500,E17,S
"Roebling, Mr. Washington Augustus II",868,0,1,male,31.0,0,0,PC 17590,50.4958,A24,S
"Carlsson, Mr. Frans Olof",873,0,1,male,33.0,0,0,695,5.0000,B51 B53 B55,S

In [ ]:
data[(data["Age"]>30) & (data["Sex"]=="male") & (data["Pclass"]==1)].sum(numeric_only=True)

PassengerId    35134.0000
Survived          27.0000
Pclass            75.0000
Age             3582.5000
SibSp             26.0000
Parch             19.0000
Fare            4829.1085
dtype: float64

In [ ]:
data[data["Pclass"].isin([1,2])].sum(numeric_only=True)

PassengerId    181761.0000
Survived          223.0000
Pclass            584.0000
Age             12280.2500
SibSp             164.0000
Parch             147.0000
Fare            21979.2542
dtype: float64

In [ ]:
data[data["Pclass"].isin([1,2])]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"McCarthy, Mr. Timothy J",7,0,1,male,54.0,0,0,17463,51.8625,E46,S
"Nasser, Mrs. Nicholas (Adele Achem)",10,1,2,female,14.0,1,0,237736,30.0708,NaN,C
"Bonnell, Miss. Elizabeth",12,1,1,female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...
"Shelley, Mrs. William (Imanita Parrish Hall)",881,1,2,female,25.0,0,1,230433,26.0000,NaN,S
"Banfield, Mr. Frederick James",884,0,2,male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
data[(data["Age"]>30) | (data["Fare"]>100)]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
"McCarthy, Mr. Timothy J",7,0,1,male,54.0,0,0,17463,51.8625,E46,S
"Bonnell, Miss. Elizabeth",12,1,1,female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...
"Vander Cruyssen, Mr. Victor",874,0,3,male,47.0,0,0,345765,9.0000,NaN,S
"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",880,1,1,female,56.0,0,1,11767,83.1583,C50,C
"Markun, Mr. Johann",882,0,3,male,33.0,0,0,349257,7.8958,NaN,S
"Rice, Mrs. William (Margaret Norton)",886,0,3,female,39.0,0,5,382652,29.1250,NaN,Q
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
data[(data["Sex"]=="female") & (data["Survived"]==1)]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",9,1,3,female,27.0,0,2,347742,11.1333,NaN,S
"Nasser, Mrs. Nicholas (Adele Achem)",10,1,2,female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
"Abelson, Mrs. Samuel (Hannah Wizosky)",875,1,2,female,28.0,1,0,P/PP 3381,24.0000,NaN,C
"Najib, Miss. Adele Kiamie ""Jane""",876,1,3,female,15.0,0,0,2667,7.2250,NaN,C
"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",880,1,1,female,56.0,0,1,11767,83.1583,C50,C
"Shelley, Mrs. William (Imanita Parrish Hall)",881,1,2,female,25.0,0,1,230433,26.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S

In [ ]:
data[(data["Sex"]=="male") & (data["Survived"]==0)]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",6,0,3,male,NaN,0,0,330877,8.4583,NaN,Q
"McCarthy, Mr. Timothy J",7,0,1,male,54.0,0,0,17463,51.8625,E46,S
"Palsson, Master. Gosta Leonard",8,0,3,male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Markun, Mr. Johann",882,0,3,male,33.0,0,0,349257,7.8958,NaN,S
"Banfield, Mr. Frederick James",884,0,2,male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
"Sutehall, Mr. Henry Jr",885,0,3,male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
data.query('Age > 30')

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
"McCarthy, Mr. Timothy J",7,0,1,male,54.0,0,0,17463,51.8625,E46,S
"Bonnell, Miss. Elizabeth",12,1,1,female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...
"Vander Cruyssen, Mr. Victor",874,0,3,male,47.0,0,0,345765,9.0000,NaN,S
"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",880,1,1,female,56.0,0,1,11767,83.1583,C50,C
"Markun, Mr. Johann",882,0,3,male,33.0,0,0,349257,7.8958,NaN,S
"Rice, Mrs. William (Margaret Norton)",886,0,3,female,39.0,0,5,382652,29.1250,NaN,Q
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
del data['PassengerId']

In [ ]:
data.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
data.drop(["Cabin","Ticket"], axis=1,inplace=True)

In [ ]:
data.rename(columns={"Fare":"TIcket_fare"},inplace=True)

In [ ]:
data.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,TIcket_fare,Embarked
Name,,,,,,,,
"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,7.2500,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,71.2833,C
"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,7.9250,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,53.1000,S
"Allen, Mr. William Henry",0,3,male,35.0,0,0,8.0500,S

In [ ]:
data.rename(columns={"PassengerId":"pass",
                     "Survived":"Jinda"},inplace=True)

In [ ]:
data.head()

,pass,Jinda,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
data["FamilySize"]=data["SibSp"]+data["Parch"]+1

In [ ]:
data.head()

,pass,Jinda,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
Name,,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,2
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S,2
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S,1